# Generated by Django 3.2.10 on 2022-03-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
